import = [
  "~/.config/alacritty/themes/themes/catppuccin.toml"
]
[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[window]
decorations = "Full"
opacity = 0.96
blur = false
option_as_alt = "Both"

[font]
normal.family = "MesloLGS NF"
size = 15
